# Generated by Django 4.2.5 on 2023-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_Update', models.CharField(max_length=100)),
                ('ScreenRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condect', models.IntegerField(blank=True, null=True)),
                ('Current_company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('Experience', models.CharField(max_length=100)),
                ('Cost', models.IntegerField()),
                ('ECTC', models.IntegerField()),
                ('Perrefered_job_location', models.CharField(max_length=500)),
                ('Notic', models.CharField(max_length=500)),
                ('Linkedin_URL', models.CharField(max_length=400)),
                ('Communication', models.CharField(max_length=500)),
                ('Feedback', models.CharField(max_length=500)),
                ('File', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
