# Generated by Django 4.2.5 on 2023-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100)),
                ('C_contact', models.IntegerField(blank=True, null=True)),
                ('CEmail', models.EmailField(max_length=254)),
                ('Caddress', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('CWebsite', models.CharField(max_length=400)),
                ('CLinkedin_URL', models.CharField(max_length=400)),
            ],
        ),
    ]
