# Generated by Django 4.2.5 on 2023-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_company_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='Cname',
            field=models.CharField(max_length=255),
        ),
    ]
