# Generated by Django 4.2.5 on 2023-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_company_detail_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='CEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
